# Generated by Django 3.1.7 on 2021-02-25 14:14 hello

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=50)),
                ('release_time', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=1000)),
                ('fit_for', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='course_picture')),
            ],
        ),
    ]
