# Generated by Django 3.1.7 on 2021-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_carausel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=models.ImageField(upload_to='course_picture'),
        ),
    ]
